Force download even when the system is set to cache central downloads
The difference of builds with caching
[ERROR]     Non-resolvable parent POM: The following artifacts could not
 be resolved: org.apache:apache:pom:33 (absent): org.apache:apache:pom:33
 was not found in https://repo1.maven.org during a previous attempt. This
 failure was cached in the local repository and resolution is not
 reattempted until the update interval of central has elapsed or updates
 are forced (remote repositories: central (https://repo1.maven.org,
 default, releases)) and parent could not be found in reactor @
 org.apache.maven.its.it0043:maven-it-it0043:1.0-SNAPSHOT,
 file:///.../its/core-it-suite/target/test-classes/mng-8181-central-repo/pom.xml,
 line 23, column 3: One or more requests failed
org.apache.maven.api.services.model.ModelResolverException: The following
 artifacts could not be resolved: org.apache:apache:pom:33 (absent):
 org.apache:apache:pom:33 was not found in https://repo1.maven.org during
 a previous attempt. This failure was cached in the local repository and
 resolution is not reattempted until the update interval of central has
 elapsed or updates are forced (remote repositories: central
 (https://repo1.maven.org, default, releases))

and without caching

[ERROR]     Non-resolvable parent POM: The following artifacts could not
 be resolved: org.apache:apache:pom:33 (absent): Could not find artifact
 org.apache:apache:pom:33 in central (https://repo1.maven.org) (remote
 repositories: central (https://repo1.maven.org, default, releases)) and
 parent could not be found in reactor @
 org.apache.maven.its.it0043:maven-it-it0043:1.0-SNAPSHOT,
 file:///.../its/core-it-suite/target/test-classes/mng-8181-central-repo/pom.xml,
 line 23, column 3: One or more requests failed
org.apache.maven.api.services.model.ModelResolverException: The following
 artifacts could not be resolved: org.apache:apache:pom:33 (absent):
 Could not find artifact org.apache:apache:pom:33 in central
 (https://repo1.maven.org) (remote repositories: central
 (https://repo1.maven.org, default, releases))

We are trying to match string that is not present ever when the failure is
cached. The closest is the string
    "central (https://repo1.maven.org, default, releases)"

So, for this test, force downloading even if the system preference is caching.