[EXPERIMENT] Halve the logging
Of the resolver (downloading vs downloaded), just report after
the fact it was downloaded (or failed to download), no need
for double lines for same resource/dependency.

This experiment includes https://github.com/apache/maven/pull/989
but does not affects it (just to create "closer" Maven to
upcoming release).

As one could expect, IT suite does fail with this change
as some ITs do assert against the build logs (but the build
itself did pass OK). Failing ITs:

[ERROR] Failures:
[ERROR]   MavenITmng6240PluginExtensionAetherProvider.testPluginExtensionDependingOnMavenAetherProvider:83->AbstractMavenIntegrationTestCase.assertEquals:668->AbstractMavenIntegrationTestCase.assertEquals:673 expected: <2> but was: <0>
[INFO]
[ERROR] Tests run: 885, Failures: 1, Errors: 0, Skipped: 80

As to be expected, the IT asserts there is log line without
progress (so DownloadING one, the one that is removed).